# Generated by Django 3.2.25 on 2026-01-17 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedDocument',
            fields=[
                ('doc_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('document', models.FileField(blank=True, max_length=200, null=True, upload_to='created_document/')),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('de', 'Deleted')], default='ac', max_length=2)),
                ('doc_type', models.CharField(choices=[('docx', 'docx'), ('pdf', 'pdf'), ('xlsx', 'xlsx'), ('html', 'html')], default='docx', max_length=20)),
                ('doc_updated_on', models.DateTimeField(auto_now=True)),
                ('doc_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_choice', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata_key', models.CharField(max_length=100, unique=True)),
                ('metadata_description', models.CharField(blank=True, max_length=200)),
                ('metadata_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('bool', 'Boolean'), ('choice', 'Choice'), ('textarea', 'TextArea'), ('image', 'Image'), ('signature', 'Signature')], max_length=10)),
                ('external_metadata', models.BooleanField(default=False)),
                ('metadata_choice', models.ManyToManyField(blank=True, related_name='metadata_keys', to='create_document_api.MetadataChoice')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('temp_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('temp_status', models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('de', 'Deleted'), ('pe', 'Pending')], default='pe', max_length=2)),
                ('temp_title', models.CharField(default='title for template', max_length=100)),
                ('temp_description', models.CharField(default='description for template', max_length=400)),
                ('upload_template', models.FileField(max_length=200, upload_to='template/')),
                ('temp_created_at', models.DateTimeField(auto_now_add=True)),
                ('temp_edited_on', models.DateTimeField(auto_now=True)),
                ('temp_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_templates', to=settings.AUTH_USER_MODEL)),
                ('temp_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMetaData',
            fields=[
                ('temp_meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_description', models.CharField(max_length=100)),
                ('temp_meta_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_metadata_items', to='create_document_api.metadatakey')),
                ('temp_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_metadata_items', to='create_document_api.template')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('meta_upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_upload_value', models.CharField(max_length=1000)),
                ('meta_created_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='create_document_api.createddocument')),
                ('meta_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='create_document_api.metadatakey')),
            ],
        ),
        migrations.AddField(
            model_name='metadatakey',
            name='metadata_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_keys', to='create_document_api.template'),
        ),
        migrations.AddField(
            model_name='createddocument',
            name='doc_matched_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to='create_document_api.template'),
        ),
    ]
