# Generated by Django 3.2.25 on 2026-01-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_document_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatemetadata',
            unique_together={('temp_metadata', 'temp_meta_key')},
        ),
    ]
