# Generated by Django 3.2.25 on 2026-01-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_document_api', '0002_alter_templatemetadata_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemetadata',
            name='temp_description',
        ),
    ]
