# Generated by Django 3.2.25 on 2026-01-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_document_api', '0003_remove_templatemetadata_temp_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatakey',
            name='metadata_origin',
        ),
    ]
